# Personal data
name = input("Enter your name: ")
postCode = input("Enter your postCode: ")
region = input("Enter your region: ")
city = input("Enter your city: ")
street = input("Enter your street: ")
buildingNumber = input("Enter a number of your building: ")
phoneNumber = input("Enter your phone number: ")
specialty = input("Enter your specialty at the university: ")
print("Your name is: ", name)
print("Your address is: ", buildingNumber+", "+street+" Street, "+city+", "+region+"  region, "+postCode)
print("Your phoneNumber is: ", phoneNumber)
print("Your specialty is: ", specialty)

# Alternative answer

name = input("Enter your name: ")
postCode = input("Enter your postCode: ")
region = input("Enter your region: ")
city = input("Enter your city: ")
street = input("Enter your street: ")
buildingNumber = input("Enter a number of your building: ")
phoneNumber = input("Enter your phone number: ")
specialty = input("Enter your specialty at the university: ")
print("Your name is: ", name)
print("Your address is: ", end='')
print(buildingNumber, end=', ')
print(street, end=', ')
print(city, end=', ')
print(region, end=', ')
print(postCode)
print("Your phoneNumber is: ", phoneNumber)
print("Your specialty is: ", specialty)

